<?php

/**
 * PluginSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: PluginSetting.class.php 28975 2010-04-05 00:26:03Z Kris.Wallsmith $
 */
abstract class PluginSetting extends BaseSetting
{

}