<?php

/*
 * This file is part of the symfony package.
 * (c) 2004, 2005 Fabien Potencier <fabien.potencier@symfony-project.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * sfGenerator is the abstract base class for all generators.
 *
 * @package    symfony
 * @subpackage generator
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id$
 */
abstract class sfGenerator
{
  abstract public function generate($generator, $class, $param);

  protected function replacePhpMarks($text)
  {
    // replace [?php and ?]
    $text = str_replace('[?php', '<?php',      $text);
    $text = str_replace('[?=',   '<?php echo', $text);
    $text = str_replace('?]',    '?>',         $text);

    return $text;
  }

  protected function evalTemplate($template_file, $clazz = __CLASS__)
  {
    // eval template template file
    ob_start();
    require($template_file);
    $content = ob_get_clean();

    // replace [?php and ?]
    $content = $this->replacePhpMarks($content);

    return $this->generateTemplate($content, $clazz);
  }

  public function generateClass($content, $clazz = __CLASS__)
  {
    $retval = "<?php\n".
              "// auto-generated by $clazz\n".
              "// date: %s\n%s\n?>";
    $retval = sprintf($retval, date('m/d/Y H:i:s'), $content);

    return $retval;
  }

  public function generateTemplate($content, $clazz = __CLASS__)
  {
    $retval = "<?php\n".
              "// auto-generated by $clazz\n".
              "// date: %s\n?>\n%s";
    $retval = sprintf($retval, date('m/d/Y H:i:s'), $content);

    return $retval;
  }
}

?>