<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
  public function retrieveArticle1(Doctrine_Query $query)
  {
    return $query->execute();
  }

  public function retrieveArticle2(array $parameters)
  {
    $query = $this->createQuery('a');
    return $query->execute();
  }

  public function retrieveArticle3(array $parameters)
  {
    $query = $this->createQuery('a');
    return $query->execute();
  }

  public function retrieveArticle4(array $parameters)
  {
    $query = $this->createQuery('a');
    return $query->fetchOne();
  }
}