<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthorTable extends Doctrine_Table
{
  public function testTableMethod()
  {
    return $this->createQuery('a')
      ->where('a.id > 0');
  }
}