<?php

/*
 * This file is part of the symfony package.
 * (c) 2004-2006 Fabien Potencier <fabien.potencier@symfony-project.com>
 * (c) 2004-2006 Sean Kerr.
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 *
 * sfDatabaseConfigHandler allows you to setup database connections in a
 * configuration file that will be created for you automatically upon first
 * request.
 *
 * @package    symfony
 * @subpackage config
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @author     Sean Kerr <skerr@mojavi.org>
 * @version    SVN: $Id$
 */
class sfDatabaseConfigHandler extends sfYamlConfigHandler
{
  /**
   * Execute this configuration handler.
   *
   * @param string An absolute filesystem path to a configuration file.
   *
   * @return string Data to be written to a cache file.
   *
   * @throws sfConfigurationException If a requested configuration file does not exist or is not readable.
   * @throws sfParseException If a requested configuration file is improperly formatted.
   */
  public function & execute ($configFile, $param = array())
  {
    // parse the yaml
    $config = $this->parseYaml($configFile);

    // merge all configuration with specific environment configuration
    $myConfig = isset($config['all']) ? $config['all'] : array();
    if (isset($config[sfConfig::get('sf_environment')]) && is_array($config[sfConfig::get('sf_environment')]))
    {
      $myConfig = sfToolkit::array_deep_merge($myConfig, $config[sfConfig::get('sf_environment')]);
    }

    // init our data and includes arrays
    $data      = array();
    $databases = array();
    $includes  = array();

    // get a list of database connections
    foreach ($myConfig as $key => $dbConfig)
    {
      // is this category already registered?
      if (in_array($key, $databases))
      {
        // this category is already registered
        $error = 'Configuration file "%s" specifies previously registered category "%s"';
        $error = sprintf($error, $configFile, $key);

        throw new sfParseException($error);
      }

      // add this database
      $databases[] = $key;

      // let's do our fancy work
      if (!isset($dbConfig['class']))
      {
        // missing class key
        $error = 'Configuration file "%s" specifies category "%s" with missing class key';
        $error = sprintf($error, $configFile, $key);

        throw new sfParseException($error);
      }

      if (isset($dbConfig['file']))
      {
        // we have a file to include
        $file =& $keys['file'];
        $file =  $this->replaceConstants($file);
        $file =  $this->replacePath($file);

        if (!is_readable($file))
        {
          // database file doesn't exist
          $error = 'Configuration file "%s" specifies class "%s" with nonexistent or unreadable file "%s"';
          $error = sprintf($error, $configFile, $dbConfig['class'], $file);

          throw new sfParseException($error);
        }

        // append our data
        $tmp        = "require_once('%s');";
        $includes[] = sprintf($tmp, $file);
      }

      // parse parameters
      $parameters = (isset($dbConfig['param']) ? var_export($dbConfig['param'], true) : 'null');

      // append new data
      $tmp = "\$database = new %s();\n" .
             "\$database->initialize(%s);\n" .
             "\$this->databases['%s'] = \$database;";

      $data[] = sprintf($tmp, $dbConfig['class'], $parameters, $key);
    }

    // compile data
    $retval = "<?php\n".
            "// auth-generated by sfDatabaseConfigHandler\n".
            "// date: %s\n%s\n%s\n?>";

    $retval = sprintf($retval, date('m/d/Y H:i:s'), implode("\n", $includes), implode("\n", $data));

    return $retval;
  }
}

?>