<?php

/*
 * This file is part of the symfony package.
 * (c) 2004-2006 Fabien Potencier <fabien.potencier@symfony-project.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * sfGeneratorConfigHandler.
 *
 * @package    symfony
 * @subpackage config
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id$
 */
class sfGeneratorConfigHandler extends sfYamlConfigHandler
{
  /**
   * Execute this configuration handler.
   *
   * @param array An array of absolute filesystem path to a configuration file.
   *
   * @return string Data to be written to a cache file.
   *
   * @throws sfConfigurationException If a requested configuration file does not exist or is not readable.
   * @throws sfParseException If a requested configuration file is improperly formatted.
   * @throws sfInitializationException If a generator.yml key check fails.
   */
  public function execute($configFiles)
  {
    // set our required categories list and initialize our handler
    $categories = array('required_categories' => array('generator'));

    $this->initialize($categories);

    // parse the yaml
    $config = $this->parseYamls($configFiles);

    $config = $config['generator'];

    if (!isset($config['class']))
    {
      $error = sprintf('Configuration file "%s" must specify a generator class directive', $configFile);

      throw new sfParseException($error);
    }

    // generator class
    $class = $config['class'];

    // generate class and add a reference to it
    $generator_manager = new sfGeneratorManager();
    $generator_manager->initialize();
    $generator_param = (isset($config['param']) ? $config['param'] : array());

    // hack to find the module name
    preg_match('#'.sfConfig::get('sf_app_module_dir_name').'/([^/]+)/#', $configFiles[0], $match);
    $generator_param['moduleName'] = $match[1];

    $data = $generator_manager->generate($class, $generator_param);

    // compile data
    $retval = "<?php\n".
              "// auto-generated by sfGeneratorConfigHandler\n".
              "// date: %s\n%s\n?>";
    $retval = sprintf($retval, date('Y/m/d H:i:s'), $data);

    return $retval;
  }
}
