<?php

/**
 * BaseResourceType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $id
 * @property string $name
 * 
 * @method enum         getId()   Returns the current record's "id" value
 * @method string       getName() Returns the current record's "name" value
 * @method ResourceType setId()   Sets the current record's "id" value
 * @method ResourceType setName() Sets the current record's "name" value
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourceType extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource_type');
        $this->hasColumn('id', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'type1',
              1 => 'type2',
              2 => 'type3',
             ),
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}