<?php

/**
 * BaseAuthor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $type
 * @property Doctrine_Collection $Articles
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getType()     Returns the current record's "type" value
 * @method Doctrine_Collection getArticles() Returns the current record's "Articles" collection
 * @method Author              setName()     Sets the current record's "name" value
 * @method Author              setType()     Sets the current record's "type" value
 * @method Author              setArticles() Sets the current record's "Articles" collection
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAuthor extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('author');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'AuthorInheritance' => 
             array(
              'type' => 'AuthorInheritance',
             ),
             'BlogAuthor' => 
             array(
              'type' => 'BlogAuthor',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'local' => 'id',
             'foreign' => 'author_id'));
    }
}