<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property User $User
 * 
 * @method integer getUserId()     Returns the current record's "user_id" value
 * @method string  getFirstName()  Returns the current record's "first_name" value
 * @method string  getLastName()   Returns the current record's "last_name" value
 * @method User    getUser()       Returns the current record's "User" value
 * @method Profile setUserId()     Sets the current record's "user_id" value
 * @method Profile setFirstName()  Sets the current record's "first_name" value
 * @method Profile setLastName()   Sets the current record's "last_name" value
 * @method Profile setUser()       Sets the current record's "User" value
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}