<?php

/**
 * BaseAuthorInheritance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuthorInheritance extends Author
{
    public function setUp()
    {
        parent::setUp();
        
    }
}