<?php

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Users
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BaseGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groups');
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('Permission as Permissions', array('refClass' => 'GroupPermission',
                                                          'local' => 'group_id',
                                                          'foreign' => 'permission_id'));

        $this->hasMany('User as Users', array('refClass' => 'UserGroup',
                                              'local' => 'group_id',
                                              'foreign' => 'user_id'));
    }
}