<?php

/**
 * BaseBlogArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BlogAuthor $Author
 * 
 * @method BlogAuthor  getAuthor() Returns the current record's "Author" value
 * @method BlogArticle setAuthor() Sets the current record's "Author" value
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBlogArticle extends Article
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogAuthor as Author', array(
             'local' => 'blog_author_id',
             'foreign' => 'id'));
    }
}