<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGroupPermission extends myDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('group_permission');
    $this->hasColumn('group_id', 'integer', null, array('type' => 'integer', 'primary' => true));
    $this->hasColumn('permission_id', 'integer', null, array('type' => 'integer', 'primary' => true));
  }

}