<?php

/**
 * BasePermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Groups
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5318 2008-12-19 20:44:54Z jwage $
 */
abstract class BasePermission extends myDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('permission');
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'length' => '255'));
  }

  public function setUp()
  {
    $this->hasMany('User as Users', array('refClass' => 'UserPermission',
                                          'local' => 'permission_id',
                                          'foreign' => 'user_id'));

    $this->hasMany('Group as Groups', array('refClass' => 'GroupPermission',
                                            'local' => 'permission_id',
                                            'foreign' => 'group_id'));
  }
}