<?php

/**
 * BaseCamelCase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property string $testCamelCase
 * @property Article $Article
 * 
 * @method integer   getArticleId()     Returns the current record's "article_id" value
 * @method string    getTestCamelCase() Returns the current record's "testCamelCase" value
 * @method Article   getArticle()       Returns the current record's "Article" value
 * @method CamelCase setArticleId()     Sets the current record's "article_id" value
 * @method CamelCase setTestCamelCase() Sets the current record's "testCamelCase" value
 * @method CamelCase setArticle()       Sets the current record's "Article" value
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCamelCase extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('camel_case');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('testCamelCase', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}