<?php

/**
 * BaseAuthorInheritance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAuthorInheritance extends Author
{
    public function setUp()
    {
        parent::setUp();
        
    }
}