<?php

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Users
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getPermissions() Returns the current record's "Permissions" collection
 * @method Doctrine_Collection getUsers()       Returns the current record's "Users" collection
 * @method Group               setName()        Sets the current record's "name" value
 * @method Group               setPermissions() Sets the current record's "Permissions" collection
 * @method Group               setUsers()       Sets the current record's "Users" collection
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseGroup extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groups');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Permission as Permissions', array(
             'refClass' => 'GroupPermission',
             'local' => 'group_id',
             'foreign' => 'permission_id'));

        $this->hasMany('User as Users', array(
             'refClass' => 'UserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));
    }
}