<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUniqueTest extends myDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('unique_test');
    $this->hasColumn('unique_test1', 'string', 255, array('type' => 'string', 'unique' => true, 'length' => '255'));
    $this->hasColumn('unique_test2', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('unique_test3', 'string', 255, array('type' => 'string', 'length' => '255'));


    $this->index('unique_test', array('fields' => array(0 => 'unique_test1', 1 => 'unique_test2'), 'type' => 'unique'));
  }

}