<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCamelCase extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('camel_case');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('testCamelCase', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id'));
    }
}