<?php

/**
 * BaseBlogAuthor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Articles
 * 
 * @method Doctrine_Collection getArticles() Returns the current record's "Articles" collection
 * @method BlogAuthor          setArticles() Sets the current record's "Articles" collection
 * 
 * @package    symfony12
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseBlogAuthor extends Author
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogArticle as Articles', array(
             'local' => 'id',
             'foreign' => 'blog_author_id'));
    }
}