<?php

/*
 * This file is part of the symfony package.
 * (c) 2004, 2005 Fabien Potencier <fabien.potencier@symfony-project>
 * (c) 2004, 2005 Sean Kerr.
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 *
 * sfDatabaseConfigHandler allows you to setup database connections in a
 * configuration file that will be created for you automatically upon first
 * request.
 *
 * @package    symfony
 * @subpackage config
 * @author     Fabien Potencier <fabien.potencier@symfony-project>
 * @author     Sean Kerr <skerr@mojavi.org>
 * @version    SVN: $Id$
 */
class sfDatabaseConfigHandler extends sfYamlConfigHandler
{
  /**
   * Execute this configuration handler.
   *
   * @param string An absolute filesystem path to a configuration file.
   *
   * @return string Data to be written to a cache file.
   *
   * @throws sfConfigurationException If a requested configuration file does not exist or is not readable.
   * @throws sfParseException If a requested configuration file is improperly formatted.
   */
  public function & execute ($configFile, $param = array())
  {
    // set our required categories list and initialize our handler
    $categories = array('required_categories' => array('databases'));

    $this->initialize($categories);

    // parse the yaml
    $config = $this->parseYaml($configFile);

    // init our data and includes arrays
    $data      = array();
    $databases = array();
    $includes  = array();

    // get a list of database connections
    foreach ($config['databases'] as $key => &$value)
    {
      $value = trim($value);

      // is this category already registered?
      if (in_array($value, $databases))
      {
        // this category is already registered
        $error = 'Configuration file "%s" specifies previously registered category "%s"';
        $error = sprintf($error, $configFile, $value);

        throw new sfParseException($error);
      }

      // see if we have the category registered for this database
      if (!isset($config[$value]))
      {
        // missing required key
        $error = 'Configuration file "%s" specifies nonexistent category "%s"';
        $error = sprintf($error, $configFile, $value);

        throw new sfParseException($error);
      }

      // add this database
      $databases[$key] = $value;
    }

    // make sure we have a default database registered
    if (!isset($databases['default']))
    {
      // missing default database
      $error = 'Configuration file "%s" must specify a default database configuration';
      $error = sprintf($error, $configFile);

      throw new sfParseException($error);
    }

    // let's do our fancy work
    foreach ($config as $category => &$keys)
    {
      if (!in_array($category, $databases))
      {
        // skip this unspecified category
        continue;
      }

      if (!isset($keys['class']))
      {
        // missing class key
        $error = 'Configuration file "%s" specifies category "%s" with missing class key';
        $error = sprintf($error, $configFile, $category);

        throw new sfParseException($error);
      }

      $class =& $keys['class'];

      if (isset($keys['file']))
      {
        // we have a file to include
        $file =& $keys['file'];
        $file =  $this->replaceConstants($file);
        $file =  $this->replacePath($file);

        if (!is_readable($file))
        {
          // database file doesn't exist
          $error = 'Configuration file "%s" specifies class "%s" with nonexistent or unreadable file "%s"';
          $error = sprintf($error, $configFile, $class, $file);

          throw new sfParseException($error);
        }

        // append our data
        $tmp        = "require_once('%s');";
        $includes[] = sprintf($tmp, $file);
      }

      // parse parameters
      $parameters = (isset($keys['param']) ? var_export($keys['param'], true) : 'null');

      // append new data
      $tmp = "\$database = new %s();\n" .
             "\$database->initialize(%s);\n" .
             "\$this->databases['%s'] = \$database;";

      $data[] = sprintf($tmp, $class, $parameters, array_search($category, $databases));
    }

    // compile data
    $retval = "<?php\n" .
            "// auth-generated by sfDatabaseConfigHandler\n" .
            "// date: %s\n%s\n%s\n?>";

    $retval = sprintf($retval, date('m/d/Y H:i:s'), implode("\n", $includes), implode("\n", $data));

    return $retval;
  }
}

?>