<?php

/*
 * This file is part of the symfony package.
 * (c) 2004, 2005 Fabien Potencier <fabien.potencier@symfony-project.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * sfGeneratorConfigHandler.
 *
 * @package    symfony
 * @subpackage config
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id$
 */
class sfGeneratorConfigHandler extends sfYamlConfigHandler
{
  /**
   * Execute this configuration handler.
   *
   * @param  string An absolute filesystem path to a configuration file.
   *
   * @return string Data to be written to a cache file.
   *
   * @throws sfConfigurationException If a requested configuration file does not exist or is not readable.
   * @throws sfParseException If a requested configuration file is improperly formatted.
   * @throws sfInitializationException If a generator.yml key check fails.
   */
  public function & execute ($configFile, $param = array())
  {
    // set our required categories list and initialize our handler
    $categories = array('required_categories' => array('generator'));

    $this->initialize($categories);

    // parse the ini
    $config = $this->parseYaml($configFile);

    $config = $config['generator'];

    // init our data
    $data = '';

    if (!isset($config['class']))
    {
      $error = 'Configuration file "%s" must specify a generator class directive';
      $error = sprintf($error, $configFile);

      throw new sfParseException($error);
    }

    // generator class
    $class = $config['class'];

    // generate class and add a reference to it
    $generator_manager = new sfGeneratorManager();
    $generator_manager->initialize();
    $generator_param = (isset($config['param']) ? $config['param'] : array());
    $param = array_merge($param, $generator_param);
    $data .= $generator_manager->generate($class, $param);

    // compile data
    $retval = "<?php\n" .
              "// auth-generated by sfGeneratorConfigHandler\n" .
              "// date: %s\n%s\n?>";
    $retval = sprintf($retval, date('m/d/Y H:i:s'), $data);

    return $retval;
  }
}

?>