<?php

/*
 * This file is part of the symfony package.
 * (c) 2004, 2005 Fabien Potencier <fabien.potencier@gmail.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @package    symfony
 * @subpackage config
 * @author     Fabien Potencier <fabien.potencier@gmail.com>
 * @version    SVN: $Id$
 */
class sfPropelConfigHandler extends sfYamlConfigHandler
{
  /**
   * Execute this configuration handler.
   *
   * @param string An absolute filesystem path to a configuration file.
   *
   * @return string Data to be written to a cache file.
   *
   * @throws sfConfigurationException If a requested configuration file does not exist or is not readable.
   * @throws sfParseException If a requested configuration file is improperly formatted.
   */
  public function & execute($configFile, $param = array())
  {
    // parse the yaml
    $config = $this->parseYaml($configFile);

    // merge all configuration with specific environment configuration
    $myConfig = $config['all'];
    if (isset($config[SF_ENVIRONMENT]) && is_array($config[SF_ENVIRONMENT]))
    {
      $myConfig = sfToolkit::array_deep_merge($myConfig, $config[SF_ENVIRONMENT]);
    }

    if (!isset($myConfig['adapter']))
    {
      // missing class key
      $error = 'Configuration file "%s" must specify "adapter" key';
      $error = sprintf($error, $configFile);

      throw new sfParseException($error);
    }

    if (!isset($myConfig['database']))
    {
      // missing database key
      $error = 'Configuration file "%s" must specify "database" key';
      $error = sprintf($error, $configFile);

      throw new sfParseException($error);
    }

    // config creation
    $configFile = <<<EOF
return array (
  'propel' =>
  array (
    'datasources' =>
    array (
      '%s' =>
      array (
        'adapter' => '%s',
        'connection' =>
        array (
          'phptype' => '%s',
          'hostspec' => '%s',
          'database' => '%s',
          'username' => '%s',
          'password' => '%s',
        ),
      ),
      'default' => '%s',
    ),
  ),
);
EOF;

    $configFile = sprintf($configFile, 
      'symfony', 
      $myConfig['adapter'], 
      $myConfig['adapter'], 
      (isset($myConfig['host']) ? $myConfig['host'] : 'localhost'), 
      $myConfig['database'], 
      (isset($myConfig['username']) ? $myConfig['username'] : ''), 
      (isset($myConfig['password']) ? $myConfig['password'] : ''),
      'symfony'
    );

    // compile data
    $retval = "<?php\n" .
              "// auth-generated by sfPropelConfigHandler\n" .
              "// date: %s\n%s\n?>";
    $retval = sprintf($retval, date('m/d/Y H:i:s'), $configFile);

    return $retval;
  }
}

?>