<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/07/06 19:58:57


$this->setDatabase('propel', new sfPropelDatabase(array (
  'phptype' => 'sqlite',
  'database' => '/var/www/production/sfweb/www/cache/symfony-for-release/1.1.8/lib/plugins/sfPropelPlugin/test/functional/fixtures/data/database.sqlite',
  'name' => 'propel',
)));
