<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2008/09/29 16:03:20


$this->setDatabase('propel', new sfPropelDatabase(array (
  'phptype' => 'sqlite',
  'database' => '/tmp/symfony-for-release/1.1.3/lib/plugins/sfPropelPlugin/test/functional/fixtures/data/database.sqlite',
  'name' => 'propel',
)));
