<?php
// auto-generated by sfValidatorConfigHandler
// date: 2009/07/06 19:58:57

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $this->context->getRequest()->setAttribute('symfony.fillin', array (
));
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validatorManager->registerName('title', 1, 'required', 'article', null, false);
  $validatorManager->registerName('body', 1, 'required', 'article', null, false);
  $this->context->getRequest()->setAttribute('symfony.fillin', array (
));
}
