<?php

/*
 * This file is part of the symfony package.
 * (c) 2004-2006 Fabien Potencier <fabien.potencier@symfony-project.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * sfGenerator is the abstract base class for all generators.
 *
 * @package    symfony
 * @subpackage generator
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id$
 */
abstract class sfGenerator
{
  protected
    $generatorClass      = '',
    $generatorManager    = null,
    $generatedModuleName = '',
    $theme               = 'default',
    $moduleName          = '';

  public function initialize($generatorManager)
  {
    $this->generatorManager = $generatorManager;
  }

  abstract public function generate($params = array());

  protected function generatePhpFiles($generatedModuleName, $templateFiles = array())
  {
    // template directory
    $template_dir = sfConfig::get('sf_symfony_data_dir').'/symfony/generator/'.$this->getGeneratorClass().'/'.$this->getTheme().'/template';

    // default template directory
    $default_template_dir = sfConfig::get('sf_symfony_data_dir').'/symfony/generator/'.$this->getGeneratorClass().'/default/template';

    // eval actions file
    $action_template = $template_dir.'/actions/actions.class.php';
    if (!is_readable($action_template))
    {
      $action_template = $default_template_dir.'/actions/actions.class.php';
    }
    $retval = $this->evalTemplate($action_template);

    // save actions class
    $this->getGeneratorManager()->getCache()->set('actions.class.php', $generatedModuleName.DIRECTORY_SEPARATOR.'actions', $retval);

    // generate template files
    foreach ($templateFiles as $template)
    {
      // eval template file
      $template_template = $template_dir.'/templates/'.$template.'.php';
      if (!is_readable($template_template))
      {
        $template_template = $default_template_dir.'/templates/'.$template.'.php';
        if (!is_readable($template_template))
        {
          // this template does not exist for this generator
          continue;
        }
      }
      $retval = $this->evalTemplate($template_template);

      // save actions class
      $this->getGeneratorManager()->getCache()->set($template.'.php', $generatedModuleName.DIRECTORY_SEPARATOR.'templates', $retval);
    }
  }

  protected function evalTemplate($template_file)
  {
    // eval template template file
    ob_start();
    require($template_file);
    $content = ob_get_clean();

    // replace [?php and ?]
    $content = $this->replacePhpMarks($content);

    $retval = "<?php\n".
              "// auto-generated by ".$this->getGeneratorClass()."\n".
              "// date: %s\n?>\n%s";
    $retval = sprintf($retval, date('m/d/Y H:i:s'), $content);

    return $retval;
  }

  protected function replacePhpMarks($text)
  {
    // replace [?php and ?]
    $text = str_replace('[?php', '<?php',      $text);
    $text = str_replace('[?=',   '<?php echo', $text);
    $text = str_replace('?]',    '?>',         $text);

    return $text;
  }

  public function getGeneratorClass()
  {
    return $this->generatorClass;
  }

  public function setGeneratorClass($generator_class)
  {
    $this->generatorClass = $generator_class;
  }

  protected function getGeneratorManager()
  {
    return $this->generatorManager;
  }

  public function getGeneratedModuleName()
  {
    return $this->generatedModuleName;
  }

  public function setGeneratedModuleName($module_name)
  {
    $this->generatedModuleName = $module_name;
  }

  public function getModuleName()
  {
    return $this->moduleName;
  }

  public function setModuleName($module_name)
  {
    $this->moduleName = $module_name;
  }

  public function getTheme()
  {
    return $this->theme;
  }

  public function setTheme($theme)
  {
    $this->theme = $theme;
  }
}

?>